### ISSUE TITLE
Caminhos longos de #include fazem com que o compilador não leia o ficheiro

### ISSUE THREAD

**Issue by Bonnie20402** [Bonnie20402/OpenRP#2]

**Comment by Bonnie20402** [comment]
Por enquanto, decidi mover os ficheiros para pastas acima.
Não sei porque isto acontece, tho.

**Comment by Chainksain** [comment]
certifique-se de que o caminho não possua nenhum caracter de espaço, muitas vezes pode ser isso o problema

**Comment by Bonnie20402** [comment]
Resolvido #pragma naked
